// Code generated by SdkContractGenerator. DO NOT EDIT.

export const contract = {
  "extend-video": {
    "models": [
      "runway"
    ],
    "fields_by_model": {
      "runway": {
        "output_resolution": {
          "enum": [
            "720p",
            "1080p"
          ],
          "required": true
        },
        "prompt": {
          "required": true
        },
        "source_task_id": {
          "required": true
        }
      }
    }
  },
  "text-to-video": {
    "models": [
      "runway"
    ],
    "fields_by_model": {
      "runway": {
        "aspect_ratio": {
          "enum": [
            "16:9",
            "9:16",
            "1:1",
            "4:3",
            "3:4"
          ]
        },
        "duration_seconds": {
          "enum": [
            5,
            10
          ],
          "required": true,
          "type": "integer"
        },
        "output_resolution": {
          "enum": [
            "720p",
            "1080p"
          ],
          "required": true
        },
        "prompt": {
          "required": true
        }
      }
    }
  }
} as const;
